# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "storage account show",
)
class Show(AAZCommand):
    """Get the properties for the specified storage account including but not limited to name, SKU name, location, and account status. The ListKeys operation should be used to retrieve storage keys.
    """

    _aaz_info = {
        "version": "2025-06-01",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.storage/storageaccounts/{}", "2025-06-01"],
        ]
    }

    def _handler(self, command_args):
        super()._handler(command_args)
        self._execute_operations()
        return self._output()

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.account_name = AAZStrArg(
            options=["-n", "--name", "--account-name"],
            help="The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.",
            required=True,
            id_part="name",
            fmt=AAZStrArgFormat(
                pattern="^[a-z0-9]+$",
                max_length=24,
                min_length=3,
            ),
        )
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )
        _args_schema.expand = AAZStrArg(
            options=["--expand"],
            help="May be used to expand the properties within account's properties. By default, data is not included when fetching properties. Currently we only support geoReplicationStats and blobRestoreStatus.",
            enum={"blobRestoreStatus": "blobRestoreStatus", "geoReplicationStats": "geoReplicationStats"},
        )
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        self.StorageAccountsGetProperties(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class StorageAccountsGetProperties(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Storage/storageAccounts/{accountName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "GET"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "accountName", self.ctx.args.account_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "$expand", self.ctx.args.expand,
                ),
                **self.serialize_query_param(
                    "api-version", "2025-06-01",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()

            _schema_on_200 = cls._schema_on_200
            _schema_on_200.extended_location = AAZObjectType(
                serialized_name="extendedLocation",
            )
            _schema_on_200.id = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200.identity = AAZIdentityObjectType()
            _schema_on_200.kind = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200.location = AAZStrType(
                flags={"required": True},
            )
            _schema_on_200.name = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200.placement = AAZObjectType()
            _schema_on_200.properties = AAZObjectType(
                flags={"client_flatten": True},
            )
            _schema_on_200.sku = AAZObjectType(
                flags={"read_only": True},
            )
            _schema_on_200.tags = AAZDictType()
            _schema_on_200.type = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200.zones = AAZListType()

            extended_location = cls._schema_on_200.extended_location
            extended_location.name = AAZStrType()
            extended_location.type = AAZStrType()

            identity = cls._schema_on_200.identity
            identity.principal_id = AAZStrType(
                serialized_name="principalId",
                flags={"read_only": True},
            )
            identity.tenant_id = AAZStrType(
                serialized_name="tenantId",
                flags={"read_only": True},
            )
            identity.type = AAZStrType(
                flags={"required": True},
            )
            identity.user_assigned_identities = AAZDictType(
                serialized_name="userAssignedIdentities",
            )

            user_assigned_identities = cls._schema_on_200.identity.user_assigned_identities
            user_assigned_identities.Element = AAZObjectType()

            _element = cls._schema_on_200.identity.user_assigned_identities.Element
            _element.client_id = AAZStrType(
                serialized_name="clientId",
                flags={"read_only": True},
            )
            _element.principal_id = AAZStrType(
                serialized_name="principalId",
                flags={"read_only": True},
            )

            placement = cls._schema_on_200.placement
            placement.zone_placement_policy = AAZStrType(
                serialized_name="zonePlacementPolicy",
            )

            properties = cls._schema_on_200.properties
            properties.access_tier = AAZStrType(
                serialized_name="accessTier",
                flags={"read_only": True},
            )
            properties.account_migration_in_progress = AAZBoolType(
                serialized_name="accountMigrationInProgress",
                flags={"read_only": True},
            )
            properties.allow_blob_public_access = AAZBoolType(
                serialized_name="allowBlobPublicAccess",
            )
            properties.allow_cross_tenant_replication = AAZBoolType(
                serialized_name="allowCrossTenantReplication",
            )
            properties.allow_shared_key_access = AAZBoolType(
                serialized_name="allowSharedKeyAccess",
            )
            properties.allowed_copy_scope = AAZStrType(
                serialized_name="allowedCopyScope",
            )
            properties.azure_files_identity_based_authentication = AAZObjectType(
                serialized_name="azureFilesIdentityBasedAuthentication",
            )
            properties.blob_restore_status = AAZObjectType(
                serialized_name="blobRestoreStatus",
                flags={"read_only": True},
            )
            properties.creation_time = AAZStrType(
                serialized_name="creationTime",
                flags={"read_only": True},
            )
            properties.custom_domain = AAZObjectType(
                serialized_name="customDomain",
                flags={"read_only": True},
            )
            properties.default_to_o_auth_authentication = AAZBoolType(
                serialized_name="defaultToOAuthAuthentication",
            )
            properties.dns_endpoint_type = AAZStrType(
                serialized_name="dnsEndpointType",
            )
            properties.dual_stack_endpoint_preference = AAZObjectType(
                serialized_name="dualStackEndpointPreference",
            )
            properties.enable_extended_groups = AAZBoolType(
                serialized_name="enableExtendedGroups",
            )
            properties.encryption = AAZObjectType(
                flags={"read_only": True},
            )
            properties.failover_in_progress = AAZBoolType(
                serialized_name="failoverInProgress",
                flags={"read_only": True},
            )
            properties.geo_priority_replication_status = AAZObjectType(
                serialized_name="geoPriorityReplicationStatus",
            )
            properties.geo_replication_stats = AAZObjectType(
                serialized_name="geoReplicationStats",
                flags={"read_only": True},
            )
            properties.immutable_storage_with_versioning = AAZObjectType(
                serialized_name="immutableStorageWithVersioning",
            )
            properties.is_hns_enabled = AAZBoolType(
                serialized_name="isHnsEnabled",
            )
            properties.is_local_user_enabled = AAZBoolType(
                serialized_name="isLocalUserEnabled",
            )
            properties.is_nfs_v3_enabled = AAZBoolType(
                serialized_name="isNfsV3Enabled",
            )
            properties.is_sftp_enabled = AAZBoolType(
                serialized_name="isSftpEnabled",
            )
            properties.is_sku_conversion_blocked = AAZBoolType(
                serialized_name="isSkuConversionBlocked",
                flags={"read_only": True},
            )
            properties.key_creation_time = AAZObjectType(
                serialized_name="keyCreationTime",
                flags={"read_only": True},
            )
            properties.key_policy = AAZObjectType(
                serialized_name="keyPolicy",
                flags={"read_only": True},
            )
            properties.large_file_shares_state = AAZStrType(
                serialized_name="largeFileSharesState",
            )
            properties.last_geo_failover_time = AAZStrType(
                serialized_name="lastGeoFailoverTime",
                flags={"read_only": True},
            )
            properties.minimum_tls_version = AAZStrType(
                serialized_name="minimumTlsVersion",
            )
            properties.network_acls = AAZObjectType(
                serialized_name="networkAcls",
                flags={"read_only": True},
            )
            properties.primary_endpoints = AAZObjectType(
                serialized_name="primaryEndpoints",
                flags={"read_only": True},
            )
            _ShowHelper._build_schema_endpoints_read(properties.primary_endpoints)
            properties.primary_location = AAZStrType(
                serialized_name="primaryLocation",
                flags={"read_only": True},
            )
            properties.private_endpoint_connections = AAZListType(
                serialized_name="privateEndpointConnections",
                flags={"read_only": True},
            )
            properties.provisioning_state = AAZStrType(
                serialized_name="provisioningState",
                flags={"read_only": True},
            )
            properties.public_network_access = AAZStrType(
                serialized_name="publicNetworkAccess",
            )
            properties.routing_preference = AAZObjectType(
                serialized_name="routingPreference",
            )
            properties.sas_policy = AAZObjectType(
                serialized_name="sasPolicy",
                flags={"read_only": True},
            )
            properties.secondary_endpoints = AAZObjectType(
                serialized_name="secondaryEndpoints",
                flags={"read_only": True},
            )
            _ShowHelper._build_schema_endpoints_read(properties.secondary_endpoints)
            properties.secondary_location = AAZStrType(
                serialized_name="secondaryLocation",
                flags={"read_only": True},
            )
            properties.status_of_primary = AAZStrType(
                serialized_name="statusOfPrimary",
                flags={"read_only": True},
            )
            properties.status_of_secondary = AAZStrType(
                serialized_name="statusOfSecondary",
                flags={"read_only": True},
            )
            properties.storage_account_sku_conversion_status = AAZObjectType(
                serialized_name="storageAccountSkuConversionStatus",
            )
            properties.supports_https_traffic_only = AAZBoolType(
                serialized_name="supportsHttpsTrafficOnly",
            )

            azure_files_identity_based_authentication = cls._schema_on_200.properties.azure_files_identity_based_authentication
            azure_files_identity_based_authentication.active_directory_properties = AAZObjectType(
                serialized_name="activeDirectoryProperties",
            )
            azure_files_identity_based_authentication.default_share_permission = AAZStrType(
                serialized_name="defaultSharePermission",
            )
            azure_files_identity_based_authentication.directory_service_options = AAZStrType(
                serialized_name="directoryServiceOptions",
                flags={"required": True},
            )
            azure_files_identity_based_authentication.smb_o_auth_settings = AAZObjectType(
                serialized_name="smbOAuthSettings",
            )

            active_directory_properties = cls._schema_on_200.properties.azure_files_identity_based_authentication.active_directory_properties
            active_directory_properties.account_type = AAZStrType(
                serialized_name="accountType",
            )
            active_directory_properties.azure_storage_sid = AAZStrType(
                serialized_name="azureStorageSid",
            )
            active_directory_properties.domain_guid = AAZStrType(
                serialized_name="domainGuid",
            )
            active_directory_properties.domain_name = AAZStrType(
                serialized_name="domainName",
            )
            active_directory_properties.domain_sid = AAZStrType(
                serialized_name="domainSid",
            )
            active_directory_properties.forest_name = AAZStrType(
                serialized_name="forestName",
            )
            active_directory_properties.net_bios_domain_name = AAZStrType(
                serialized_name="netBiosDomainName",
            )
            active_directory_properties.sam_account_name = AAZStrType(
                serialized_name="samAccountName",
            )

            smb_o_auth_settings = cls._schema_on_200.properties.azure_files_identity_based_authentication.smb_o_auth_settings
            smb_o_auth_settings.is_smb_o_auth_enabled = AAZBoolType(
                serialized_name="isSmbOAuthEnabled",
            )

            blob_restore_status = cls._schema_on_200.properties.blob_restore_status
            blob_restore_status.failure_reason = AAZStrType(
                serialized_name="failureReason",
                flags={"read_only": True},
            )
            blob_restore_status.parameters = AAZObjectType(
                flags={"read_only": True},
            )
            blob_restore_status.restore_id = AAZStrType(
                serialized_name="restoreId",
                flags={"read_only": True},
            )
            blob_restore_status.status = AAZStrType(
                flags={"read_only": True},
            )

            parameters = cls._schema_on_200.properties.blob_restore_status.parameters
            parameters.blob_ranges = AAZListType(
                serialized_name="blobRanges",
                flags={"required": True},
            )
            parameters.time_to_restore = AAZStrType(
                serialized_name="timeToRestore",
                flags={"required": True},
            )

            blob_ranges = cls._schema_on_200.properties.blob_restore_status.parameters.blob_ranges
            blob_ranges.Element = AAZObjectType()

            _element = cls._schema_on_200.properties.blob_restore_status.parameters.blob_ranges.Element
            _element.end_range = AAZStrType(
                serialized_name="endRange",
                flags={"required": True},
            )
            _element.start_range = AAZStrType(
                serialized_name="startRange",
                flags={"required": True},
            )

            custom_domain = cls._schema_on_200.properties.custom_domain
            custom_domain.name = AAZStrType(
                flags={"required": True},
            )
            custom_domain.use_sub_domain_name = AAZBoolType(
                serialized_name="useSubDomainName",
            )

            dual_stack_endpoint_preference = cls._schema_on_200.properties.dual_stack_endpoint_preference
            dual_stack_endpoint_preference.publish_ipv6_endpoint = AAZBoolType(
                serialized_name="publishIpv6Endpoint",
            )

            encryption = cls._schema_on_200.properties.encryption
            encryption.identity = AAZObjectType()
            encryption.key_source = AAZStrType(
                serialized_name="keySource",
            )
            encryption.keyvaultproperties = AAZObjectType()
            encryption.require_infrastructure_encryption = AAZBoolType(
                serialized_name="requireInfrastructureEncryption",
            )
            encryption.services = AAZObjectType()

            identity = cls._schema_on_200.properties.encryption.identity
            identity.federated_identity_client_id = AAZStrType(
                serialized_name="federatedIdentityClientId",
            )
            identity.user_assigned_identity = AAZStrType(
                serialized_name="userAssignedIdentity",
            )

            keyvaultproperties = cls._schema_on_200.properties.encryption.keyvaultproperties
            keyvaultproperties.current_versioned_key_expiration_timestamp = AAZStrType(
                serialized_name="currentVersionedKeyExpirationTimestamp",
                flags={"read_only": True},
            )
            keyvaultproperties.current_versioned_key_identifier = AAZStrType(
                serialized_name="currentVersionedKeyIdentifier",
                flags={"read_only": True},
            )
            keyvaultproperties.keyname = AAZStrType()
            keyvaultproperties.keyvaulturi = AAZStrType()
            keyvaultproperties.keyversion = AAZStrType()
            keyvaultproperties.last_key_rotation_timestamp = AAZStrType(
                serialized_name="lastKeyRotationTimestamp",
                flags={"read_only": True},
            )

            services = cls._schema_on_200.properties.encryption.services
            services.blob = AAZObjectType()
            _ShowHelper._build_schema_encryption_service_read(services.blob)
            services.file = AAZObjectType()
            _ShowHelper._build_schema_encryption_service_read(services.file)
            services.queue = AAZObjectType()
            _ShowHelper._build_schema_encryption_service_read(services.queue)
            services.table = AAZObjectType()
            _ShowHelper._build_schema_encryption_service_read(services.table)

            geo_priority_replication_status = cls._schema_on_200.properties.geo_priority_replication_status
            geo_priority_replication_status.is_blob_enabled = AAZBoolType(
                serialized_name="isBlobEnabled",
            )

            geo_replication_stats = cls._schema_on_200.properties.geo_replication_stats
            geo_replication_stats.can_failover = AAZBoolType(
                serialized_name="canFailover",
                flags={"read_only": True},
            )
            geo_replication_stats.can_planned_failover = AAZBoolType(
                serialized_name="canPlannedFailover",
                flags={"read_only": True},
            )
            geo_replication_stats.last_sync_time = AAZStrType(
                serialized_name="lastSyncTime",
                flags={"read_only": True},
            )
            geo_replication_stats.post_failover_redundancy = AAZStrType(
                serialized_name="postFailoverRedundancy",
                flags={"read_only": True},
            )
            geo_replication_stats.post_planned_failover_redundancy = AAZStrType(
                serialized_name="postPlannedFailoverRedundancy",
                flags={"read_only": True},
            )
            geo_replication_stats.status = AAZStrType(
                flags={"read_only": True},
            )

            immutable_storage_with_versioning = cls._schema_on_200.properties.immutable_storage_with_versioning
            immutable_storage_with_versioning.enabled = AAZBoolType()
            immutable_storage_with_versioning.immutability_policy = AAZObjectType(
                serialized_name="immutabilityPolicy",
            )

            immutability_policy = cls._schema_on_200.properties.immutable_storage_with_versioning.immutability_policy
            immutability_policy.allow_protected_append_writes = AAZBoolType(
                serialized_name="allowProtectedAppendWrites",
            )
            immutability_policy.immutability_period_since_creation_in_days = AAZIntType(
                serialized_name="immutabilityPeriodSinceCreationInDays",
            )
            immutability_policy.state = AAZStrType()

            key_creation_time = cls._schema_on_200.properties.key_creation_time
            key_creation_time.key1 = AAZStrType()
            key_creation_time.key2 = AAZStrType()

            key_policy = cls._schema_on_200.properties.key_policy
            key_policy.key_expiration_period_in_days = AAZIntType(
                serialized_name="keyExpirationPeriodInDays",
                flags={"required": True},
            )

            network_acls = cls._schema_on_200.properties.network_acls
            network_acls.bypass = AAZStrType()
            network_acls.default_action = AAZStrType(
                serialized_name="defaultAction",
                flags={"required": True},
            )
            network_acls.ip_rules = AAZListType(
                serialized_name="ipRules",
            )
            network_acls.ipv6_rules = AAZListType(
                serialized_name="ipv6Rules",
            )
            network_acls.resource_access_rules = AAZListType(
                serialized_name="resourceAccessRules",
            )
            network_acls.virtual_network_rules = AAZListType(
                serialized_name="virtualNetworkRules",
            )

            ip_rules = cls._schema_on_200.properties.network_acls.ip_rules
            ip_rules.Element = AAZObjectType()
            _ShowHelper._build_schema_ip_rule_read(ip_rules.Element)

            ipv6_rules = cls._schema_on_200.properties.network_acls.ipv6_rules
            ipv6_rules.Element = AAZObjectType()
            _ShowHelper._build_schema_ip_rule_read(ipv6_rules.Element)

            resource_access_rules = cls._schema_on_200.properties.network_acls.resource_access_rules
            resource_access_rules.Element = AAZObjectType()

            _element = cls._schema_on_200.properties.network_acls.resource_access_rules.Element
            _element.resource_id = AAZStrType(
                serialized_name="resourceId",
            )
            _element.tenant_id = AAZStrType(
                serialized_name="tenantId",
            )

            virtual_network_rules = cls._schema_on_200.properties.network_acls.virtual_network_rules
            virtual_network_rules.Element = AAZObjectType()

            _element = cls._schema_on_200.properties.network_acls.virtual_network_rules.Element
            _element.action = AAZStrType()
            _element.id = AAZStrType(
                flags={"required": True},
            )
            _element.state = AAZStrType()

            private_endpoint_connections = cls._schema_on_200.properties.private_endpoint_connections
            private_endpoint_connections.Element = AAZObjectType()

            _element = cls._schema_on_200.properties.private_endpoint_connections.Element
            _element.id = AAZStrType(
                flags={"read_only": True},
            )
            _element.name = AAZStrType(
                flags={"read_only": True},
            )
            _element.properties = AAZObjectType(
                flags={"client_flatten": True},
            )
            _element.type = AAZStrType(
                flags={"read_only": True},
            )

            properties = cls._schema_on_200.properties.private_endpoint_connections.Element.properties
            properties.private_endpoint = AAZObjectType(
                serialized_name="privateEndpoint",
            )
            properties.private_link_service_connection_state = AAZObjectType(
                serialized_name="privateLinkServiceConnectionState",
                flags={"required": True},
            )
            properties.provisioning_state = AAZStrType(
                serialized_name="provisioningState",
                flags={"read_only": True},
            )

            private_endpoint = cls._schema_on_200.properties.private_endpoint_connections.Element.properties.private_endpoint
            private_endpoint.id = AAZStrType(
                flags={"read_only": True},
            )

            private_link_service_connection_state = cls._schema_on_200.properties.private_endpoint_connections.Element.properties.private_link_service_connection_state
            private_link_service_connection_state.action_required = AAZStrType(
                serialized_name="actionRequired",
            )
            private_link_service_connection_state.description = AAZStrType()
            private_link_service_connection_state.status = AAZStrType()

            routing_preference = cls._schema_on_200.properties.routing_preference
            routing_preference.publish_internet_endpoints = AAZBoolType(
                serialized_name="publishInternetEndpoints",
            )
            routing_preference.publish_microsoft_endpoints = AAZBoolType(
                serialized_name="publishMicrosoftEndpoints",
            )
            routing_preference.routing_choice = AAZStrType(
                serialized_name="routingChoice",
            )

            sas_policy = cls._schema_on_200.properties.sas_policy
            sas_policy.expiration_action = AAZStrType(
                serialized_name="expirationAction",
                flags={"required": True},
            )
            sas_policy.sas_expiration_period = AAZStrType(
                serialized_name="sasExpirationPeriod",
                flags={"required": True},
            )

            storage_account_sku_conversion_status = cls._schema_on_200.properties.storage_account_sku_conversion_status
            storage_account_sku_conversion_status.end_time = AAZStrType(
                serialized_name="endTime",
                flags={"read_only": True},
            )
            storage_account_sku_conversion_status.sku_conversion_status = AAZStrType(
                serialized_name="skuConversionStatus",
                flags={"read_only": True},
            )
            storage_account_sku_conversion_status.start_time = AAZStrType(
                serialized_name="startTime",
                flags={"read_only": True},
            )
            storage_account_sku_conversion_status.target_sku_name = AAZStrType(
                serialized_name="targetSkuName",
            )

            sku = cls._schema_on_200.sku
            sku.name = AAZStrType(
                flags={"required": True},
            )
            sku.tier = AAZStrType(
                flags={"read_only": True},
            )

            tags = cls._schema_on_200.tags
            tags.Element = AAZStrType()

            zones = cls._schema_on_200.zones
            zones.Element = AAZStrType()

            return cls._schema_on_200


class _ShowHelper:
    """Helper class for Show"""

    _schema_encryption_service_read = None

    @classmethod
    def _build_schema_encryption_service_read(cls, _schema):
        if cls._schema_encryption_service_read is not None:
            _schema.enabled = cls._schema_encryption_service_read.enabled
            _schema.key_type = cls._schema_encryption_service_read.key_type
            _schema.last_enabled_time = cls._schema_encryption_service_read.last_enabled_time
            return

        cls._schema_encryption_service_read = _schema_encryption_service_read = AAZObjectType()

        encryption_service_read = _schema_encryption_service_read
        encryption_service_read.enabled = AAZBoolType()
        encryption_service_read.key_type = AAZStrType(
            serialized_name="keyType",
        )
        encryption_service_read.last_enabled_time = AAZStrType(
            serialized_name="lastEnabledTime",
            flags={"read_only": True},
        )

        _schema.enabled = cls._schema_encryption_service_read.enabled
        _schema.key_type = cls._schema_encryption_service_read.key_type
        _schema.last_enabled_time = cls._schema_encryption_service_read.last_enabled_time

    _schema_endpoints_read = None

    @classmethod
    def _build_schema_endpoints_read(cls, _schema):
        if cls._schema_endpoints_read is not None:
            _schema.blob = cls._schema_endpoints_read.blob
            _schema.dfs = cls._schema_endpoints_read.dfs
            _schema.file = cls._schema_endpoints_read.file
            _schema.internet_endpoints = cls._schema_endpoints_read.internet_endpoints
            _schema.ipv6_endpoints = cls._schema_endpoints_read.ipv6_endpoints
            _schema.microsoft_endpoints = cls._schema_endpoints_read.microsoft_endpoints
            _schema.queue = cls._schema_endpoints_read.queue
            _schema.table = cls._schema_endpoints_read.table
            _schema.web = cls._schema_endpoints_read.web
            return

        cls._schema_endpoints_read = _schema_endpoints_read = AAZObjectType(
            flags={"read_only": True}
        )

        endpoints_read = _schema_endpoints_read
        endpoints_read.blob = AAZStrType(
            flags={"read_only": True},
        )
        endpoints_read.dfs = AAZStrType(
            flags={"read_only": True},
        )
        endpoints_read.file = AAZStrType(
            flags={"read_only": True},
        )
        endpoints_read.internet_endpoints = AAZObjectType(
            serialized_name="internetEndpoints",
        )
        cls._build_schema_storage_account_internet_endpoints_read(endpoints_read.internet_endpoints)
        endpoints_read.ipv6_endpoints = AAZObjectType(
            serialized_name="ipv6Endpoints",
        )
        endpoints_read.microsoft_endpoints = AAZObjectType(
            serialized_name="microsoftEndpoints",
        )
        cls._build_schema_storage_account_microsoft_endpoints_read(endpoints_read.microsoft_endpoints)
        endpoints_read.queue = AAZStrType(
            flags={"read_only": True},
        )
        endpoints_read.table = AAZStrType(
            flags={"read_only": True},
        )
        endpoints_read.web = AAZStrType(
            flags={"read_only": True},
        )

        ipv6_endpoints = _schema_endpoints_read.ipv6_endpoints
        ipv6_endpoints.blob = AAZStrType(
            flags={"read_only": True},
        )
        ipv6_endpoints.dfs = AAZStrType(
            flags={"read_only": True},
        )
        ipv6_endpoints.file = AAZStrType(
            flags={"read_only": True},
        )
        ipv6_endpoints.internet_endpoints = AAZObjectType(
            serialized_name="internetEndpoints",
        )
        cls._build_schema_storage_account_internet_endpoints_read(ipv6_endpoints.internet_endpoints)
        ipv6_endpoints.microsoft_endpoints = AAZObjectType(
            serialized_name="microsoftEndpoints",
        )
        cls._build_schema_storage_account_microsoft_endpoints_read(ipv6_endpoints.microsoft_endpoints)
        ipv6_endpoints.queue = AAZStrType(
            flags={"read_only": True},
        )
        ipv6_endpoints.table = AAZStrType(
            flags={"read_only": True},
        )
        ipv6_endpoints.web = AAZStrType(
            flags={"read_only": True},
        )

        _schema.blob = cls._schema_endpoints_read.blob
        _schema.dfs = cls._schema_endpoints_read.dfs
        _schema.file = cls._schema_endpoints_read.file
        _schema.internet_endpoints = cls._schema_endpoints_read.internet_endpoints
        _schema.ipv6_endpoints = cls._schema_endpoints_read.ipv6_endpoints
        _schema.microsoft_endpoints = cls._schema_endpoints_read.microsoft_endpoints
        _schema.queue = cls._schema_endpoints_read.queue
        _schema.table = cls._schema_endpoints_read.table
        _schema.web = cls._schema_endpoints_read.web

    _schema_ip_rule_read = None

    @classmethod
    def _build_schema_ip_rule_read(cls, _schema):
        if cls._schema_ip_rule_read is not None:
            _schema.action = cls._schema_ip_rule_read.action
            _schema.value = cls._schema_ip_rule_read.value
            return

        cls._schema_ip_rule_read = _schema_ip_rule_read = AAZObjectType()

        ip_rule_read = _schema_ip_rule_read
        ip_rule_read.action = AAZStrType()
        ip_rule_read.value = AAZStrType(
            flags={"required": True},
        )

        _schema.action = cls._schema_ip_rule_read.action
        _schema.value = cls._schema_ip_rule_read.value

    _schema_storage_account_internet_endpoints_read = None

    @classmethod
    def _build_schema_storage_account_internet_endpoints_read(cls, _schema):
        if cls._schema_storage_account_internet_endpoints_read is not None:
            _schema.blob = cls._schema_storage_account_internet_endpoints_read.blob
            _schema.dfs = cls._schema_storage_account_internet_endpoints_read.dfs
            _schema.file = cls._schema_storage_account_internet_endpoints_read.file
            _schema.web = cls._schema_storage_account_internet_endpoints_read.web
            return

        cls._schema_storage_account_internet_endpoints_read = _schema_storage_account_internet_endpoints_read = AAZObjectType()

        storage_account_internet_endpoints_read = _schema_storage_account_internet_endpoints_read
        storage_account_internet_endpoints_read.blob = AAZStrType(
            flags={"read_only": True},
        )
        storage_account_internet_endpoints_read.dfs = AAZStrType(
            flags={"read_only": True},
        )
        storage_account_internet_endpoints_read.file = AAZStrType(
            flags={"read_only": True},
        )
        storage_account_internet_endpoints_read.web = AAZStrType(
            flags={"read_only": True},
        )

        _schema.blob = cls._schema_storage_account_internet_endpoints_read.blob
        _schema.dfs = cls._schema_storage_account_internet_endpoints_read.dfs
        _schema.file = cls._schema_storage_account_internet_endpoints_read.file
        _schema.web = cls._schema_storage_account_internet_endpoints_read.web

    _schema_storage_account_microsoft_endpoints_read = None

    @classmethod
    def _build_schema_storage_account_microsoft_endpoints_read(cls, _schema):
        if cls._schema_storage_account_microsoft_endpoints_read is not None:
            _schema.blob = cls._schema_storage_account_microsoft_endpoints_read.blob
            _schema.dfs = cls._schema_storage_account_microsoft_endpoints_read.dfs
            _schema.file = cls._schema_storage_account_microsoft_endpoints_read.file
            _schema.queue = cls._schema_storage_account_microsoft_endpoints_read.queue
            _schema.table = cls._schema_storage_account_microsoft_endpoints_read.table
            _schema.web = cls._schema_storage_account_microsoft_endpoints_read.web
            return

        cls._schema_storage_account_microsoft_endpoints_read = _schema_storage_account_microsoft_endpoints_read = AAZObjectType()

        storage_account_microsoft_endpoints_read = _schema_storage_account_microsoft_endpoints_read
        storage_account_microsoft_endpoints_read.blob = AAZStrType(
            flags={"read_only": True},
        )
        storage_account_microsoft_endpoints_read.dfs = AAZStrType(
            flags={"read_only": True},
        )
        storage_account_microsoft_endpoints_read.file = AAZStrType(
            flags={"read_only": True},
        )
        storage_account_microsoft_endpoints_read.queue = AAZStrType(
            flags={"read_only": True},
        )
        storage_account_microsoft_endpoints_read.table = AAZStrType(
            flags={"read_only": True},
        )
        storage_account_microsoft_endpoints_read.web = AAZStrType(
            flags={"read_only": True},
        )

        _schema.blob = cls._schema_storage_account_microsoft_endpoints_read.blob
        _schema.dfs = cls._schema_storage_account_microsoft_endpoints_read.dfs
        _schema.file = cls._schema_storage_account_microsoft_endpoints_read.file
        _schema.queue = cls._schema_storage_account_microsoft_endpoints_read.queue
        _schema.table = cls._schema_storage_account_microsoft_endpoints_read.table
        _schema.web = cls._schema_storage_account_microsoft_endpoints_read.web


__all__ = ["Show"]
